# Generated by Django 3.0.6 on 2020-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Czy aktywna pizzeria'),
        ),
    ]
