# Generated by Django 2.2.7 on 2019-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0004_auto_20191120_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pizza_premium',
            field=models.BooleanField(default=False, verbose_name='Pizza freestyle?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pizza_freestyle',
            field=models.BooleanField(default=False, verbose_name='Pizza premium?'),
        ),
        migrations.DeleteModel(
            name='ProductPriceSize',
        ),
    ]
