# Generated by Django 2.2.7 on 2019-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0011_auto_20191124_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sms_send',
            field=models.BooleanField(default=False, verbose_name='Sms'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='start_delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Czas wywozu'),
        ),
    ]
