# Generated by Django 2.2.7 on 2019-12-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0016_auto_20191203_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='extra_3',
            new_name='extra_3_topps_price',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='extra_4',
            new_name='extra_4_topps_price',
        ),
    ]
