# Generated by Django 2.2.7 on 2019-12-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0017_auto_20191203_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionorder',
            name='toppings_change_minus',
        ),
        migrations.RemoveField(
            model_name='positionorder',
            name='toppings_change_minus_other_side',
        ),
        migrations.RemoveField(
            model_name='positionorder',
            name='toppings_change_plus',
        ),
        migrations.RemoveField(
            model_name='positionorder',
            name='toppings_change_plus_other_side',
        ),
    ]
