# Generated by Django 2.2.7 on 2019-12-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0020_remove_positionorder_toppings_on_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionorder',
            name='toppings',
        ),
    ]
