# Generated by Django 2.2.7 on 2019-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0021_remove_positionorder_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='extra_price_right',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cena dodatków na prawej'),
        ),
    ]
