# Generated by Django 2.2.7 on 2019-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0022_positionorder_extra_price_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='change_topps_info_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Id o zmianie składników'),
        ),
        migrations.AddField(
            model_name='positionorder',
            name='change_topps_info_right_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Id o zmianie składników na prawej'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='change_topps_info',
            field=models.CharField(blank=True, default='', max_length=1012, null=True, verbose_name='Info o zmianie składników'),
        ),
    ]
