# Generated by Django 2.2.7 on 2019-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0023_auto_20191209_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='change_topps_info_id',
            field=models.CharField(blank=True, default="'", max_length=256, null=True, verbose_name='Id o zmianie składników'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='change_topps_info_right_id',
            field=models.CharField(blank=True, default="'", max_length=256, null=True, verbose_name='Id o zmianie składników na prawej'),
        ),
    ]
