# Generated by Django 2.2.7 on 2019-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0024_auto_20191209_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='extra_price_left',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cena dodatków na prawej'),
        ),
    ]
