# Generated by Django 2.2.7 on 2019-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0025_positionorder_extra_price_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='freestyle_toppings',
            field=models.ManyToManyField(blank=True, related_name='order_position_toppings', to='babilon_v1.Products', verbose_name='Dodatki'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_pizza_freestyle',
            field=models.BooleanField(default=False, verbose_name='Pizza freestyle?'),
        ),
    ]
