# Generated by Django 2.2.7 on 2019-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0026_auto_20191212_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='type_of_cost',
        ),
        migrations.AddField(
            model_name='purchases',
            name='pay_method',
            field=models.IntegerField(choices=[(0, 'Zakup towarów'), (1, 'Wypłata pracownikom'), (2, 'Podatki/ZUS'), (3, 'Koszta stałe'), (4, 'Inne wydatki')], default='1', verbose_name='Rodzaj wydatku: '),
        ),
    ]
