# Generated by Django 2.2.7 on 2019-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0027_auto_20191217_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='const_cost',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='paymethod',
        ),
        migrations.AddField(
            model_name='purchases',
            name='type_purchases',
            field=models.IntegerField(choices=[(0, 'Zakup towarów'), (1, 'Wypłata pracownikom'), (2, 'Podatki/ZUS'), (3, 'Koszta stałe'), (4, 'Inne wydatki')], default='0', verbose_name='Rodzaj kosztu: '),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='pay_method',
            field=models.IntegerField(choices=[(1, 'Gotówka'), (2, 'Karta'), (3, 'Przelew')], default='1', verbose_name='Rodzaj wydatku: '),
        ),
    ]
