# Generated by Django 2.2.7 on 2019-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0028_auto_20191217_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='info',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Nazwa'),
        ),
    ]
