# Generated by Django 2.2.7 on 2019-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0029_purchases_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='printed',
            field=models.BooleanField(default=True, verbose_name='Wydrukowano paragon?'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='info',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Info'),
        ),
    ]
