# Generated by Django 2.2.7 on 2020-01-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0030_auto_20191225_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pizza_freestyle',
        ),
        migrations.AlterField(
            model_name='products',
            name='pizza_premium',
            field=models.BooleanField(default=False, verbose_name='Pizza premium?'),
        ),
    ]
