# Generated by Django 2.2.7 on 2020-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0033_products_code_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Kod produktu'),
        ),
    ]
