# Generated by Django 2.2.7 on 2020-01-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0034_auto_20200110_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('category', 'pizza_number', 'type_of_ingredient', 'product_name', 'product_size'), 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='orders',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Promocja'),
        ),
    ]
