# Generated by Django 3.0.2 on 2020-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0040_auto_20200118_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sms_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Czas smsa'),
        ),
    ]
