# Generated by Django 3.0.3 on 2020-02-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0045_auto_20200214_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuniety'), to='babilon_v1.Products', verbose_name='Product na zamówieniu'),
        ),
    ]
