# Generated by Django 3.0.3 on 2020-02-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon_v1', '0047_auto_20200214_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon_v1.Products', verbose_name='Product na zamówieniu'),
        ),
    ]
