# Generated by Django 2.2.5 on 2019-10-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer telefonu pracownika'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='work_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='work_in', to='babilon.Pizzeria', verbose_name='Zatrudniony w:'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='work_in_today',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Pizzeria', verbose_name='Miejsce pracy dzisiaj'),
        ),
    ]
