# Generated by Django 2.2.5 on 2019-10-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0002_auto_20191003_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='work_in',
            field=models.ManyToManyField(blank=True, related_name='work_in', to='babilon.Pizzeria', verbose_name='Zatrudniony w:'),
        ),
    ]
