# Generated by Django 2.2.5 on 2019-10-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0003_auto_20191003_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Osoba'},
        ),
    ]
