# Generated by Django 2.2.5 on 2019-10-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0004_auto_20191003_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
