# Generated by Django 2.2.5 on 2019-10-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0005_auto_20191003_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kategoria produktu')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa productu')),
                ('pizza', models.BooleanField(blank=True, null=True, verbose_name='Pizza?')),
                ('drink', models.BooleanField(blank=True, null=True, verbose_name='Napój?')),
                ('pizza_components', models.IntegerField(choices=[(1, 'Warzywny'), (2, 'Mięsny')], verbose_name='Rodzaj składnika')),
                ('cake', models.BooleanField(blank=True, null=True, verbose_name='Składnik do ciasta?')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64, verbose_name='Rozmiar')),
                ('pizza', models.BooleanField(blank=True, null=True, verbose_name='Pizza')),
                ('bottle', models.BooleanField(blank=True, null=True, verbose_name='Butelka')),
                ('sauce', models.BooleanField(blank=True, null=True, verbose_name='Sos')),
                ('pizza_box', models.BooleanField(blank=True, null=True, verbose_name='Sos')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa pizzy')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Numer pizzy')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Cena pizzy')),
                ('componets', models.ManyToManyField(related_name='Pizza_components', to='babilon.Products', verbose_name='Składniki')),
                ('pizza_size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pizza_size', to='babilon.ProductSize', verbose_name='Rozmiar pizzy')),
            ],
        ),
    ]
