# Generated by Django 2.2.5 on 2019-10-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0008_auto_20191003_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_size', to='babilon.ProductSize', verbose_name='Rozmiar'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=128, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pizza_components',
            field=models.IntegerField(blank=True, choices=[(1, 'Warzywny'), (2, 'Mięsny'), (3, 'Podstawowy'), (4, 'Wyrób ciasta')], null=True, verbose_name='Rodzaj składnika'),
        ),
    ]
