# Generated by Django 2.2.5 on 2019-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0009_auto_20191003_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cena produktu'),
        ),
    ]
