# Generated by Django 2.2.5 on 2019-10-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0010_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vatrate', models.IntegerField(blank=True, null=True, verbose_name='Stawka VAT')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Vat', verbose_name='Stawka VAT'),
        ),
    ]
