# Generated by Django 2.2.5 on 2019-10-03 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0011_auto_20191003_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_size',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Numer zamówienia')),
                ('status', models.IntegerField(choices=[(1, 'Przyjęte'), (2, 'Potwierdzone'), (3, 'W przygotowanie'), (4, 'Gotowe'), (5, 'W dostawie'), (6, 'Wydane'), (7, 'Nieodebrane'), (8, 'Zrealizowane')], default=1, verbose_name='Status zamówienia')),
                ('paymethod', models.IntegerField(choices=[(1, 'Gotówka'), (2, 'Karta'), (3, 'Online')], default=1, verbose_name='Status zamówienia')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Clients', verbose_name='Klient')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kierowca')),
                ('order', models.ManyToManyField(to='babilon.Products', verbose_name='Zamówione produkty')),
            ],
        ),
    ]
