# Generated by Django 2.2.5 on 2019-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0012_auto_20191003_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.AddField(
            model_name='orders',
            name='client',
            field=models.ManyToManyField(blank=True, to='babilon.Pizza', verbose_name='Jaka pizza'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.ManyToManyField(to='babilon.Products', verbose_name='Dodatkowe produkty'),
        ),
    ]
