# Generated by Django 2.2.5 on 2019-10-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0013_auto_20191003_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pizza_size', to='babilon.ProductSize', verbose_name='Rozmiar pizzy'),
        ),
    ]
