# Generated by Django 2.2.5 on 2019-10-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0014_pizza_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pizza',
            field=models.ManyToManyField(blank=True, to='babilon.Pizza', verbose_name='Jaka pizza'),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.AddField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Clients', verbose_name='Klient'),
        ),
    ]
