# Generated by Django 2.2.5 on 2019-10-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0015_auto_20191003_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order',
            new_name='other',
        ),
    ]
