# Generated by Django 2.2.5 on 2019-10-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0016_auto_20191003_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kategoria menu')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='componets',
            field=models.ManyToManyField(related_name='pizza_component', to='babilon.Products', verbose_name='Składniki'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_size', to='babilon.ProductSize', verbose_name='Rozmiar pizzy'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='menu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_menu', to='babilon.MainMenu', verbose_name='Kategroia w Menu'),
        ),
    ]
