# Generated by Django 2.2.5 on 2019-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0017_auto_20191003_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_freestyle',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pizza freestyle'),
        ),
    ]
