# Generated by Django 2.2.5 on 2019-10-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0018_pizza_pizza_freestyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='menu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_menu', to='babilon.MainMenu', verbose_name='Kategroia w Menu'),
        ),
    ]
