# Generated by Django 2.2.5 on 2019-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0020_auto_20191003_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pizza_componets',
            field=models.ManyToManyField(blank=True, related_name='pizza_component', to='babilon.Products', verbose_name='Składniki'),
        ),
    ]
