# Generated by Django 2.2.5 on 2019-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0021_auto_20191003_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='qouantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Ilosc'),
        ),
    ]
