# Generated by Django 2.2.5 on 2019-10-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0022_products_qouantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='qouantity',
            new_name='quantity',
        ),
    ]
