# Generated by Django 2.2.5 on 2019-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0023_auto_20191004_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('menu_category', 'name')},
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rabat'),
        ),
    ]
