# Generated by Django 2.2.5 on 2019-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0024_auto_20191004_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
