# Generated by Django 2.2.5 on 2019-10-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0025_orders_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
