# Generated by Django 2.2.5 on 2019-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0026_auto_20191004_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('size',)},
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.IntegerField(choices=[(1, 'Lokal'), (2, 'Dostawa'), (3, 'On-line lokal'), (4, 'On-line dostawa')], default=1, verbose_name='Rodzaj zamówienia'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aktywne'), (2, 'Potwierdzone'), (3, 'W przygotowaniu'), (4, 'Gotowe'), (5, 'W dostawie'), (6, 'Wydane'), (7, 'Nieodebrane'), (8, 'Zrealizowane')], default=1, verbose_name='Status zamówienia'),
        ),
    ]
