# Generated by Django 2.2.5 on 2019-10-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0027_auto_20191005_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Adress'),
        ),
    ]
