# Generated by Django 2.2.5 on 2019-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0028_orders_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time_get',
            field=models.TimeField(blank=True, null=True, verbose_name='Czas wywywozu'),
        ),
        migrations.AddField(
            model_name='orders',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Czas dostarczenia'),
        ),
    ]
