# Generated by Django 2.2.5 on 2019-10-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0029_auto_20191005_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa dodatku')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Cena za dodatek')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping_size', to='babilon.ProductSize', verbose_name='Rozmiar')),
            ],
            options={
                'ordering': ('name', 'size'),
            },
        ),
    ]
