# Generated by Django 2.2.5 on 2019-10-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0030_toppingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='babilon.ToppingCategory', verbose_name='Categoria dodatki pizzy'),
        ),
    ]
