# Generated by Django 2.2.5 on 2019-10-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0031_products_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena produktu'),
        ),
    ]
