# Generated by Django 2.2.5 on 2019-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0032_auto_20191005_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='change_info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Zaminy w składnikach'),
        ),
    ]
