# Generated by Django 2.2.5 on 2019-10-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0033_products_change_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64, verbose_name='Rozmiar pizzy')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa składniku')),
                ('category', models.IntegerField(choices=[(1, 'Podstawowy'), (2, 'Serowy'), (3, 'Warzywny'), (4, 'Mięsny')], verbose_name='Rodzaj dodatku')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena składnika')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping_size', to='babilon.PizzaSize', verbose_name='Rozmiar pizzy')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa pizzy')),
                ('change_toppings', models.CharField(blank=True, max_length=128, null=True, verbose_name='Zaminy w składnikach')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena produktu')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_size', to='babilon.PizzaSize', verbose_name='Rozmiar pizzy')),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='babilon.Toppings', verbose_name='Składniki')),
            ],
        ),
    ]
