# Generated by Django 2.2.5 on 2019-10-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0034_pizza_pizzasize_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skladniki', to='babilon.Pizza'),
        ),
    ]
