# Generated by Django 2.2.5 on 2019-10-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0036_auto_20191005_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='babilon.MainMenu', verbose_name='Kategroia w Menu'),
        ),
    ]
