# Generated by Django 2.2.5 on 2019-10-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0037_pizza_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ('name', 'size')},
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='category',
            new_name='menu_category',
        ),
    ]
