# Generated by Django 2.2.5 on 2019-10-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0038_auto_20191006_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='change_toppings',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Zaminy w składnikach'),
        ),
        migrations.AlterField(
            model_name='products',
            name='menu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_menu', to='babilon.MainMenu', verbose_name='Kategoria w Menu'),
        ),
    ]
