# Generated by Django 2.2.5 on 2019-10-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0039_auto_20191006_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='change_toppings',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Zaminy w składnikach'),
        ),
    ]
