# Generated by Django 2.2.5 on 2019-10-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0040_auto_20191006_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='extra_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Cena za dodatki'),
        ),
    ]
