# Generated by Django 2.2.5 on 2019-10-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0041_products_extra_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128, verbose_name='Pozycja zamówienia')),
                ('change_topps', models.CharField(max_length=128, verbose_name='Zmiany składników')),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Cena dodatków')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena podstawowa')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='pozition_order', to='babilon.PositionOrder', verbose_name='Pozycja zamowienia'),
        ),
    ]
