# Generated by Django 2.2.5 on 2019-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0042_auto_20191006_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Ilosc'),
        ),
    ]
