# Generated by Django 2.2.5 on 2019-10-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0044_auto_20191006_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizza_toppings', to='babilon.Products', verbose_name='Składniki'),
        ),
    ]
