# Generated by Django 2.2.6 on 2019-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0045_positionorder_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pizza_componets',
            new_name='toppings',
        ),
        migrations.RemoveField(
            model_name='products',
            name='beff_topps_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cake_topps_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='change_info',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cheese_topps_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='products',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='products',
            name='vege_topps_price',
        ),
        migrations.AddField(
            model_name='products',
            name='number_in_menu',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='Rabat'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='beef_topps_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena dodatku mięsnego'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='cheese_topps_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena dodatku serowego'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='sauce_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena dodatkowego sosu'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='vege_topps_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Cena dodatku warzywnego'),
        ),
    ]
