# Generated by Django 2.2.6 on 2019-10-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0047_auto_20191008_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='number_in_menu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rabat'),
        ),
    ]
