# Generated by Django 2.2.6 on 2019-10-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0048_auto_20191008_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='number_in_menu',
        ),
    ]
