# Generated by Django 2.2.6 on 2019-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0049_remove_products_number_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_in_menu',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Rabat'),
        ),
    ]
