# Generated by Django 2.2.6 on 2019-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0050_products_number_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='change_topps',
            field=models.CharField(default='', max_length=128, verbose_name='Zmiany składników'),
        ),
        migrations.AlterField(
            model_name='products',
            name='component',
            field=models.IntegerField(blank=True, choices=[(1, 'Warzywny'), (2, 'Mięsny'), (3, 'Serowy'), (4, 'Podstawowy'), (5, 'Wyrób ciasta')], null=True, verbose_name='component'),
        ),
    ]
