# Generated by Django 2.2.6 on 2019-10-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0051_auto_20191008_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='other',
            field=models.ManyToManyField(null=True, to='babilon.Products', verbose_name='Dodatkowe produkty'),
        ),
        migrations.AlterField(
            model_name='products',
            name='component',
            field=models.IntegerField(blank=True, choices=[(1, 'Warzywny'), (2, 'Mięsny'), (3, 'Serowy'), (4, 'Podstawowy'), (5, 'Wyrób ciasta'), (6, 'Sosy płatne'), (7, 'Sosy darmowe')], null=True, verbose_name='component'),
        ),
    ]
