# Generated by Django 2.2.6 on 2019-10-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0052_auto_20191008_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='other',
            field=models.ManyToManyField(blank=True, to='babilon.Products', verbose_name='Dodatkowe produkty'),
        ),
    ]
