# Generated by Django 2.2.6 on 2019-10-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0053_auto_20191008_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='number_in_menu',
        ),
    ]
