# Generated by Django 2.2.6 on 2019-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0054_remove_products_number_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='extra_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena dodatków'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena podstawowa'),
        ),
        migrations.AlterField(
            model_name='products',
            name='extra_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena dodatków'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena podstawowa'),
        ),
    ]
