# Generated by Django 2.2.6 on 2019-10-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0056_auto_20191010_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='change_topps',
            field=models.CharField(default='', max_length=256, verbose_name='Zmiany składników'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='position',
            field=models.CharField(max_length=512, verbose_name='Pozycja zamówienia'),
        ),
    ]
