# Generated by Django 2.2.6 on 2019-10-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0057_auto_20191012_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='change_topps',
            field=models.CharField(default='', max_length=512, verbose_name='Zmiany składników'),
        ),
    ]
