# Generated by Django 2.2.6 on 2019-10-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0058_auto_20191013_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionorder',
            name='toppings',
        ),
        migrations.AddField(
            model_name='positionorder',
            name='discount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cena podstawowa'),
        ),
        migrations.AddField(
            model_name='positionorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Orders', verbose_name='Zamówienie nr.'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babilon.Products', verbose_name='Pozycja zamówienia'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Ilosc'),
        ),
    ]
