# Generated by Django 2.2.6 on 2019-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0059_auto_20191013_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='extra_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cena dodatków'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='price',
            field=models.FloatField(verbose_name='Cena podstawowa'),
        ),
    ]
