# Generated by Django 2.2.6 on 2019-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0060_auto_20191013_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='extra_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cena dodatków'),
        ),
    ]
