# Generated by Django 2.2.6 on 2019-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0061_auto_20191013_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='discount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Rabat'),
        ),
    ]
