# Generated by Django 2.2.6 on 2019-10-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0062_auto_20191013_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cake_info',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Zaminy w składnikach'),
        ),
        migrations.AddField(
            model_name='products',
            name='change_extra_toppings',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Zaminy w składnikach'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rabat'),
        ),
        migrations.AlterField(
            model_name='products',
            name='component',
            field=models.IntegerField(blank=True, choices=[(1, 'Warzywny'), (2, 'Mięsny'), (3, 'Serowy'), (4, 'Dodatki extra'), (5, 'Rodzaj ciasta'), (6, 'Sosy płatne'), (7, 'Sosy darmowe')], null=True, verbose_name='component'),
        ),
    ]
