# Generated by Django 2.2.6 on 2019-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0063_auto_20191016_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('menu_category', 'name', 'size')},
        ),
        migrations.AddField(
            model_name='positionorder',
            name='info',
            field=models.CharField(default='', max_length=256, verbose_name='Informacje'),
        ),
    ]
