# Generated by Django 2.2.6 on 2019-10-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0064_auto_20191017_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='add_sauces',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Sosy'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='info',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Informacje'),
        ),
    ]
