# Generated by Django 2.2.6 on 2019-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0065_auto_20191017_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionorder',
            name='add_sauces',
        ),
        migrations.AddField(
            model_name='positionorder',
            name='add_sauces_free',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Sosy darmowe'),
        ),
        migrations.AddField(
            model_name='positionorder',
            name='add_sauces_pay',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Sosy płatne'),
        ),
    ]
