# Generated by Django 2.2.6 on 2019-10-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0066_auto_20191017_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pizzeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Pizzeria', verbose_name='Pizzeria'),
        ),
    ]
