# Generated by Django 2.2.6 on 2019-10-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0067_orders_pizzeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Numer zamówienia'),
        ),
    ]
