# Generated by Django 2.2.6 on 2019-10-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0068_auto_20191018_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='productsize',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Menu_rozmiar', to='babilon.MainMenu', verbose_name='Rozmiar kategori'),
        ),
    ]
