# Generated by Django 2.2.6 on 2019-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0070_auto_20191021_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-number',)},
        ),
        migrations.AddField(
            model_name='productsize',
            name='extra_topps_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena dodatku extra_1'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymethod',
            field=models.IntegerField(choices=[(1, 'Gotówka'), (2, 'Karta'), (3, 'Online')], default=1, verbose_name='Płatność zamówienia'),
        ),
    ]
