# Generated by Django 2.2.6 on 2019-10-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0071_auto_20191021_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionorder',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='products',
            name='pizza_freestyle',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pizza freestyle'),
        ),
    ]
