# Generated by Django 2.2.6 on 2019-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0072_auto_20191023_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pizza_freestyle',
            field=models.BooleanField(default=False, verbose_name='Pizza freestyle'),
        ),
    ]
