# Generated by Django 2.2.6 on 2019-10-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0073_auto_20191023_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='cake_info',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Zaminy w składnikach'),
        ),
    ]
