# Generated by Django 2.2.6 on 2019-10-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0074_positionorder_cake_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionorder',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='positionorder',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizza_extra_toppings', to='babilon.Products', verbose_name='Dodatki'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='cake_info',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Zmiany ciasta'),
        ),
    ]
