# Generated by Django 2.2.6 on 2019-10-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0075_auto_20191029_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='halfpizza_info',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Lewa lub prawa'),
        ),
    ]
