# Generated by Django 2.2.6 on 2019-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0076_positionorder_halfpizza_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='pizza_half',
            field=models.BooleanField(default=False, verbose_name='Pizza pol_na_pol'),
        ),
        migrations.AddField(
            model_name='positionorder',
            name='toppings_right',
            field=models.ManyToManyField(blank=True, related_name='pizza_extra_toppings_on_right', to='babilon.Products', verbose_name='Dodatki_na_praej'),
        ),
    ]
