# Generated by Django 2.2.6 on 2019-10-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0077_auto_20191030_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionorder',
            old_name='halfpizza_info',
            new_name='halfpizza_name',
        ),
    ]
