# Generated by Django 2.2.6 on 2019-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0078_auto_20191030_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionorder',
            name='toppings_right',
        ),
        migrations.AddField(
            model_name='positionorder',
            name='change_topps_on_right',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Zmiany składników na prawej'),
        ),
    ]
