# Generated by Django 2.2.6 on 2019-10-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0079_auto_20191030_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Products', verbose_name='Pozycja zamówienia'),
        ),
    ]
