# Generated by Django 2.2.6 on 2019-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0080_auto_20191030_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionorder',
            name='halfpizza_name',
            field=models.CharField(blank=True, default='', max_length=126, null=True, verbose_name='Lewa lub prawa'),
        ),
    ]
