# Generated by Django 2.2.6 on 2019-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0081_auto_20191030_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-data',)},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='lastname',
        ),
        migrations.AddField(
            model_name='clients',
            name='firstlastname',
            field=models.CharField(default='', max_length=128, verbose_name='Imię Nazwisko'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Info'),
        ),
    ]
