# Generated by Django 2.2.6 on 2019-10-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0082_auto_20191031_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='adress',
            new_name='adrress',
        ),
        migrations.AlterField(
            model_name='clients',
            name='firstlastname',
            field=models.CharField(max_length=128, verbose_name='Imię Nazwisko'),
        ),
    ]
