# Generated by Django 2.2.6 on 2019-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0083_auto_20191031_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Licznik wyboru'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='firstlastname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Imię Nazwisko'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.IntegerField(choices=[(1, 'Lokal'), (2, 'Wywóz'), (3, 'Dostawa')], default=1, verbose_name='Rodzaj zamówienia'),
        ),
    ]
