# Generated by Django 2.2.6 on 2019-11-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0085_auto_20191103_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='street',
            new_name='address',
        ),
    ]
