# Generated by Django 2.2.6 on 2019-11-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0086_auto_20191103_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Licznik wyboru'),
        ),
    ]
