# Generated by Django 2.2.6 on 2019-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0087_auto_20191103_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('quantity',)},
        ),
        migrations.AlterField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address'),
        ),
    ]
