# Generated by Django 2.2.6 on 2019-11-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0088_auto_20191103_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babilon.Address', verbose_name='Adres'),
        ),
    ]
