# Generated by Django 2.2.6 on 2019-11-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0089_auto_20191103_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='adress',
            new_name='address',
        ),
    ]
