# Generated by Django 2.2.6 on 2019-11-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0090_auto_20191103_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.IntegerField(choices=[(1, 'Lokal'), (2, 'Wynos'), (3, 'Dostawa')], default=1, verbose_name='Rodzaj zamówienia'),
        ),
    ]
