# Generated by Django 2.2.6 on 2019-11-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0091_auto_20191103_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='data',
        ),
    ]
