# Generated by Django 2.2.6 on 2019-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilon', '0092_auto_20191103_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-data',)},
        ),
        migrations.AddField(
            model_name='orders',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
